### ISSUE TITLE
Bitnami changed nginx "vhost" location

### ISSUE THREAD

**Issue by trash-80** [Kovah/LinkAce#153]
After hours of troubleshooting, I found that apparently since docker-compose.production.yml was last updated, Bitnami changed the location of mounting conf files to 'server_blocks': 
`
if ! is_dir_empty "$NGINX_VOLUME_DIR/conf/vhosts"; then
error "Custom server blocks files were found inside '$NGINX_VOLUME_DIR/conf/vhosts'. This configuration is not supported anymore. Please mount your custom server blocks config files at '${NGINX_SERVER_BLOCKS_DIR}' instead."
`
and:
`The recommended mount point for adding custom server blocks changes from '/opt/bitnami/nginx/conf/vhosts' to '/opt/bitnami/nginx/conf/server_blocks'. Remember to update your Docker Compose files to user the new mount point.`

This is a good reason not to set images to "latest"

**Comment by Kovah** [comment]
Hi!
Setup with Docker was completely overhauled in the past weeks, because there were multiple issues with it. The new state is just not yet "released".
If you are searching for the new, working version, please have a look at the development version: https://github.com/Kovah/LinkAce/blob/dev/docker-compose.production.yml
I also created a unified Docker image containing both PHP and Nginx, which is a bit simpler to use.

**Comment by trash-80** [comment]
Hey, thanks.

I thought I was in 'dev', but I think I switched to master when I couldn't get everything working.  I'll try to play in there once again.
This can be closed, thank you for the quick reply.
