### ISSUE TITLE
Simple search box always opened on main screen

### ISSUE THREAD

**Issue by DeRuiterIndustrieleAutomatisering** [Kovah/LinkAce#192]
** Is there a way to simplify search in the list? I find it cumbersome to click on the search icon, go to a new screen and enter my search criteria.

** Is it possible to show a edit box on the main screen that's always shown? The results can be shown in a dropdown list.

**Comment by Kovah** [comment]
Will think about how this can be  improves. I have no issues with an additional click as I do not search for links that often and I prefer the full search interface instead of a simple box with no options.

**Comment by jimmybrancaccio** [comment]
I am 100% for this. I keep using the add new link field as a search box because for whatever reason my brain thinks that's what it is.

I search for links all the time - I mean what else is this tool for besides storing them.

This one seems like an easy win, just add a search form in the header where the search icon is. It looks like Bootstrap is being used so this should be quite a trivial addition.
