### ISSUE TITLE
Create specific list corresponding to respective folder in bookmarks.html while importing

### ISSUE THREAD

**Issue by rwjack** [Kovah/LinkAce#193]
**Is your feature request related to a problem? Please describe.**
When importing from a bookmarks.html file, I figure it would be easier to add the imported links to a specific list, and also to have sub-lists for each folder in bookmarks.html.

**Describe the solution you'd like**
Eg. If I have 3 folders (a,b,c) with 2 links each (a1, a2 in a, b1, b2 in b, c1, c2 in c) in my bookmarks.html, importing the file should create 3 new lists instead of tags (4 if I'm creating everything in a sub-list, eg. desktop-bookmarks, so the hierarchy should be desktop-bookmarks/a/a1 & a2 ; desktop-bookmarks/b/b1 & b2; desktop-bookmarks/c/c1 & c2), and place the bookmarks in their respective lists.

**Comment by ibasaw** [comment]
same issue, it create tags instead of list !?

**Comment by Kovah** [comment]
Unfortunately, I have to close this without any solution. It's nearly impossible to get the import from a browser export right because all vendors do their own little tweaks and mess with the structure. Also, lists are probably not the right taxonomy for folder structures as used in browser bookmarks. LinkAce might get (nested) folders later.
