### ISSUE TITLE
Can‘t add more than one emoji tag

### ISSUE THREAD

**Issue by jk** [Kovah/LinkAce#206]
**Describe the bug**
I want to add multiple tags which only consist of an emoji. One is possible, multiple are not. 

**To Reproduce**
1. Go to 'Add tag'
2. Enter '🇩🇪'
3. Click add tag
4. Go to 'Add tag'
5. Enter '🇬🇧'
6. Click add tag
7. Error message 'name already exists'

**Expected behavior**
That's it's possible to add several emoji named tags. 

**LinkAce setup (please complete the following information):**
 - Version: latest - 1.0.1
 - Installed via: Docker
 - OS: Ubuntu

**Comment by Kovah** [comment]
This sounds weird. Will check this later.

**Comment by Kovah** [comment]
I have to digg deeper into this, because LinkAce behaves weirdly when it comes to single Emojis.
Adding 🇩🇪 and then 🇬🇧 leads to "name exists". 
But adding 🇩🇪 and then ⚡ works without issues.
Must be related to how Emojis are actually encoded and how Laravel validation / MySQL comparisons works.

**Comment by Kovah** [comment]
Ok. It's definitely MySQL.
Changing the table collation from `utf8mb4_unicode_ci` to `utf8mb4_bin` works, more detail [in this post](https://stackoverflow.com/questions/41147829/how-can-i-search-by-emoji-in-mysql-using-utf8mb4).

Changing character encoding with existing data is always a bad idea, but you could try that if you want to use the emojis: https://stackoverflow.com/a/38995859

I will check if it makes sense to set utf8mb4_bin as the default for future LinkAce installations. Otherwise I will add a hint to the docs.

**Comment by Kovah** [comment]
I decided to set `utf8mb4_bin` as the default collation in the Docker compose templates. It provides proper support for all unicode characters, including Emoji. I will also add a hint to the wiki.
