### ISSUE TITLE
Support for Markdown in descriptions and notes

### ISSUE THREAD

**Issue by Kovah** [Kovah/LinkAce#217]
Feature request from #214 by @jk

**Comment by u6k** [comment]
Hello, Kovah.

I would like to use LinkAce, a great bookmark management application, and I am thinking of migrating from my bookmark notes. Many of my bookmark notes are written in Markdown, so I'm very pleased that this Issue is being addressed.

Is there any plan to support this Issue in the near future? If not, I will look into the possibility of using markedjs to implement it.

**Comment by Kovah** [comment]
It should be quite easy to implement because the underlying framework supports Markdown rendering by default. I would implement this first, without any WYSIWYG editor.

**Comment by u6k** [comment]
Thank you for your answer, I see that I can parse it with Laravel's Illuminate/Mail/Markdown. I understand now.
