### ISSUE TITLE
Error - Database could not be configured (Linkace with SQLite)

### ISSUE THREAD

**Issue by cinetube** [Kovah/LinkAce#335]
![2021-12-14 20 54 20 192 168 137 128 991b50508686](https://user-images.githubusercontent.com/23441775/146022062-1982ebaa-fcdb-4c23-a7b8-1355de33aa8e.jpg)

Database could not be configured. Please check your connection details. Details: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')

How to resolve this error

![2021-12-14 20 55 08 192 168 137 128 2ca35d658992](https://user-images.githubusercontent.com/23441775/146022220-13270704-be78-405a-9232-e65570d445bf.jpg)

**Comment by Kovah** [comment]
Hi, as written in the documentation, you should not use the built-in installer because it does not support SQLite yet.
https://www.linkace.org/docs/v1/setup/setup-with-sqlite/

**Comment by Drallas** [comment]
Adding to this issue.

Since i had to abandon mu efforts on Qnap, using an Ubuntu host for now.

All seems  good until i bump into this.. **Error - Database could not be configured (Linkace with SQLite)** issue

Followed steps from https://www.linkace.org/docs/v1/setup/setup-with-sqlite/ but still redirected to setup/start page forcing this DB check that then fails..

**Comment by Drallas** [comment]
.env SETUP_COMPLETED=true fixed it! 😄

Documentation seems not 100% accurate.
