### ISSUE TITLE
LinkAce taking extremely long to import URLs

### ISSUE THREAD

**Issue by cinetube** [Kovah/LinkAce#336]
LinkAce taking extremely long to import URLs from an HTML file. It took around 10 minutes to import around 200 URLs from an HTML file. How to resolve this issue?

**Comment by Kovah** [comment]
That can be caused by websites responding slowly. LinkAce will fetch data of all websites when they are imported. If you want to skip this data generation, use the command line with the `--skip-meta-generation` option. See the [docs](https://www.linkace.org/docs/v1/cli/#import-links-from-a-html-bookmarks-file).

**Comment by Kovah** [comment]
If you still have problems, feel free to re-open the issue.
