### ISSUE TITLE
Docs incomplete (Mail configuration)

### ISSUE THREAD

**Issue by denis-ev** [Kovah/LinkAce#471]
**Describe the bug**
Got LinkAce working and wanted to setup Mail and Backups, for the Backups to work the docs say you need to setup the mail configuration. I found the configuration only my searching the files and looking through the commits. 

The .env.example should include ALL possible configuration and NOT only the bare minimum.

**Comment by Kovah** [comment]
Hi, it's quite a hassle with the .env file because some users only want the bare minimum, others want all in it. 🤷 
Anyway, I updated the documentation to include more details about the email and backup configuration.

See https://www.linkace.org/docs/v1/setup/post-setup/ and https://www.linkace.org/docs/v1/configuration/application-backups/
(The latter page already has a complete documentation for backups, please use the search.)
