### ISSUE TITLE
Overhaul of the UI of links, lists and tags

### ISSUE THREAD

**Issue by Kovah** [Kovah/LinkAce#553]
The current UI is good, but not really consistent. Especially links are displayed in many different ways across the application.

**Please add your ideas and design inspiration.**

---

LinkAce should have buttons to change the view directly on the page, with more options being available in the settings to configure it. [completionist.me](https://completionist.me) has a really nice UI to change how games are displayed, notice the toggles in the top right. Something similar could be adapted for LinkAce.

One minimal view that only shows the most important infos, like the current "list with less details" option.
<img width="1149" alt="Bildschirmfoto 2022-10-17 um 09 08 40" src="https://user-images.githubusercontent.com/1816101/196111843-19a1d3b7-5180-4e19-8b94-fe88189e9243.png">

One view that shows more infos, but does not visually overload the UI.
<img width="1157" alt="Bildschirmfoto 2022-10-17 um 09 08 51" src="https://user-images.githubusercontent.com/1816101/196111848-4f301e2c-bc83-4b97-a513-ce40b094e593.png">

A card view that shows a lot of information but also is more heavy.
<img width="1136" alt="Bildschirmfoto 2022-10-17 um 09 09 03" src="https://user-images.githubusercontent.com/1816101/196111850-baf2e26e-a444-4893-9628-9a8b51da35f5.png">

The same should be done with lists and tags.

---

The following issues should be taken into consideration while working on the UI:
- #479
- #444
- #443
- #442 
- #441 
- #438
- #437
- #435
- #434
- #433

**Comment by Creling** [comment]
IMHO, the list view and the card view are both classic and are adopted by plenty of apps. And the next thing is to decide which attributions of a link should be display in each view.

For me, the title, the tags, the lists and the time added are important for both views and the description are needed in the card view.

**Comment by Creling** [comment]
To be honest, I think hierarchy tags (i,e. #a/b) are better than the current used organization system (i.e. tags + lists).

**Comment by jacobgkau** [comment]
> To be honest, I think hierarchy tags (i,e. #a/b) are better than the current used organization system (i.e. tags + lists).

I think that allowing tags to act more like tags (being able to search by tag with "and" and "not", effectively) would address a lot of additional use cases: https://github.com/Kovah/LinkAce/discussions/545 

I used to prefer folder structures, but after writing my own bookmark manager with folders, I'm starting to wish that I had tags so I could find things easier. I realized that combinations of tags can easily make up the functionality of a folder. E.g. instead of having a "2022/News" folder, I can have a "2022" tag and a "News" tag, and I can search for "2022 News" if I want to see what would be in that "folder."

Similarly, in the case of a tag hierarchy, if tags functioned properly and allowed you to at least search with "and", there's nothing stopping you from using a tag naming convention that makes clear to you which tags "go inside" of which other tags (basically, which tags are more general and which are more specific.) I'm not sure that hierarchy needs to be explicitly supported in the code to meet your desired use case, if searching is properly/fully supported.

I do agree that lists seem a little superfluous in addition to tags, especially since lists can't have hierarchy either (so they're essentially just single-use tags.)

**Comment by amadeusp** [comment]
For me personally a UI that offers options for 1. minimal, 2. minimal + thumbnails and 3. one that displays the links as cards with large preview images is sufficient.

**Comment by Creling** [comment]
@jacobgkau 
> I used to prefer folder structures, but after writing my own bookmark manager with folders, I'm starting to wish that I had tags so I could find things easier. I realized that combinations of tags can easily make up the functionality of a folder. E.g. instead of having a "2022/News" folder, I can have a "2022" tag and a "News" tag, and I can search for "2022 News" if I want to see what would be in that "folder." 

Using tags with logical conjunctions is a nice workflow when searching somthing. However, it will be a bit painful when saving pages.

Suppose that I am doing some research in filed A and find something useful. I will tag the page with '#Field/Field-A/Concept-B' in a hierarchy-tag system or with '#Field #Field-A #Concept-B' in a multi-tag system.

The difference is, the hierarchy structure itself is a kind of hint when tagging things, no to mention that I could benefit from autocomplete. But in the latter situation, I might not remember what the parent tag of a certain tag is, and must type in three individual tags manually.

The hierarchy-tag structure is a more flexible folder structure, which means you do not need to create folder manually and you could put a page in multiply folders.

**Comment by habitats-tech** [comment]
I believe a combination of lists and tags is welcome. Lists are similar to folders and can be used for searching, while tags are useful for filtering, as well as for searching. The concept of lists/tags is very similar to how relational databases work with tables/entities and fields/attributes.

For example I might have multiple links under a list (e.g. maths), while I can filter the maths list based on tags (e.g. #algebra, #geometry, #algebra and geometry, #algebra or #geometry, etc.). Sometimes a tag name is applicable to multiple lists so searching for the specific tag name might not be useful in all situations; although a hierarchical tag system can solve this issue.

However I believe lists are valuable, even with a hierarchical tag system in place.

**Comment by chrissawyerfan4** [comment]
Not precisely the links, lists and tags themselves, but I have made changes to their menu entries in my local version of LinkAce. Instead of the, pardon, inconsistent default version where links have dedicated menu entries for adding and viewing, but then lists and tags use a submenu for *both* adding and viewing, and then lots of unused space to the right of that, I have... well, showing is easier than telling :)

Original:  
![showing the current menu structure](https://github.com/Kovah/LinkAce/assets/126926647/f0014b37-6a5e-41d1-88b5-27af461bd805)

Consistified:  
![each of LLT is a menu entry, with a plus behind it for adding](https://github.com/Kovah/LinkAce/assets/126926647/eec6e61c-3ed4-4e2c-a874-ef29b8658356)

Clicking the word goes to the overview of links, lists, or tags, and clicking the + behind it goes to the adding page.

What I don't yet like is that there is no obvious link between the + and the item it belongs with, but for me it's an improvement.

An advantage of the submenus variant is that it could show (some of) the lists and tags, e.g. favorited lists/tags or the most recently added/updated/viewed or so. Could also still have both: click on the word to go to the respective page; click on a fold-out to get options like Add and the 5 most recently added ones, for example.

**Comment by Kovah** [comment]
So, I've come up with those three ways how links are displayed:

### Simple
Basically like the current one, but with additional option to open share buttons.
![link-display-simple](https://github.com/Kovah/LinkAce/assets/1816101/f0e4230f-2484-4288-964b-33d69ad0a44b)

### Detailed
Extended list more similar to apps like Pinboard. Shows more details but doesn't overload the UI.
![link-display-detailed](https://github.com/Kovah/LinkAce/assets/1816101/8a613998-6fdb-4adc-a680-05fda13ca113)
### Cards
Large cards similar to apps like Raindrop, including thumbnails and more details.
![link-display-cards](https://github.com/Kovah/LinkAce/assets/1816101/3f0e165a-3ad5-46bf-94ea-55567794060a)

---

All three options are available where links are displayed: link lists, tags and lists. The table view was removed.

The option can be toggled from the top of the list: 
![toggle-preview](https://github.com/Kovah/LinkAce/assets/1816101/9f0b77f3-5f1b-4ec0-8769-a49acdf273e1)

**Comment by amadeusp** [comment]
I like it! Maybe the Detailed view could show thumbnails as well?

**Comment by jacobgkau** [comment]
The way I wrote [my alternative app](https://github.com/nerdonthestreet/nilamark) basically looks like Simple except it also shows the favicon. Since the favicon is only as large as a single line of text anyway, I don't see why it should be omitted from Simple. (I agree with @amadeusp that a smaller thumbnail could go nicely on the left or right of the Detailed view, to maybe balance out how much text there is in that one.)

Proper tag searching functionality would be more important to me than any UI aspects, though.

**Comment by Kovah** [comment]
Marking this as completed for now, later feedback will be implemented in future versions.
