### ISSUE TITLE
Add option to disable link checks for a link

### ISSUE THREAD

**Issue by Kovah** [Kovah/LinkAce#93]
Currently, broken links are checked on every new run of the link checks. There should be some logic to turn off those checks after some failed checks or let the user disable checks for a particular link manually.

**Comment by naquad** [comment]
What about global check disabling? Quite a few of my bookmarks require authorization, behind CloudFlare, or internal (resources in VPNs), so I get a lot of failed check reports.

For now, I've just commented out the scheduled task, but it would be nice to have a setting for this (environment/system settings screen). I still want to run cron because of the backups, though.

P. S. Sorry for posting into the closed ticket, I just found it way too relevant to create a new one.

**Comment by Kovah** [comment]
Will take this into consideration for v2 which I'm working on.
